---
title: Siteleaf
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
highlighter: pygments
markdown: kramdown
permalink: pretty
sass:
  style: compressed
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
